name: Build and Deploy Code

# other e.g on: push or on: pull_request 

on: ["push", "pull_request"]
  
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to kelvin
        run: echo "hello kelvin"
